apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.className}}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: {{.Values.storageType}}
