apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-{{.Values.ingressClass}}
spec:
  acme:
    email: {{.Values.acme.email}}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-{{.Values.ingressClass}}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{.Values.ingressClass}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-{{.Values.ingressClass}}
spec:
  acme:
    email: {{.Values.acme.email}}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-{{.Values.ingressClass}}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{.Values.ingressClass}}
