apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dnsping
  namespace: argocd
spec:
  destination:
    namespace: dnsping
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/manifests/dnsping
    repoURL: https://github.com/alleaffengaffen/banana-bread
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
